packages:
  - "apps/*"
  # all packages in direct subdirs of packages/
  - 'packages/*'
  - 'packages/ui/*'
  # all packages in subdirs of components/
  # - 'components/**'
  # exclude packages that are inside test directories
  # - '!**/test/**'